"""added column to animes

Revision ID: 445759649bb3
Revises: 76176ab73d4e
Create Date: 2023-12-02 20:55:24.855078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445759649bb3'
down_revision: Union[str, None] = '76176ab73d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animes', 'image_url')
    # ### end Alembic commands ###
