"""added animes model

Revision ID: 76176ab73d4e
Revises: 9c8375d75ecc
Create Date: 2023-12-02 20:48:40.000691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76176ab73d4e'
down_revision: Union[str, None] = '9c8375d75ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animes',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('english_name', sa.String(), nullable=False),
    sa.Column('other_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('genres', sa.String(), nullable=False),
    sa.Column('synopsis', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('episodes', sa.String(), nullable=False),
    sa.Column('aired', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('anime_id')
    )
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['role_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['role_id'])
    op.drop_table('animes')
    # ### end Alembic commands ###
